//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclareDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string maql { get; set; }
        public string maphong { get; set; }
        public string hotenql { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
    }
}
