//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclareDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string maphong { get; set; }
        public string tenphong { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
